version: '2'

services:
  man:
    build: .
    image: holmantai/carnd_t2:latest
    network_mode: "host"
    command: sh /carND/EKDP/build/build.sh
    volumes:
      - .:/carND/EKDP
    # stdin_open: true
    # tty: true
