version: '2'

services:
  man:
    build: .
    image: holmantai/carnd_t2_ukfp:latest
    network_mode: "host"
    command: sh /carND/UKFP/build/build.sh
    volumes:
      - .:/carND/UKFP
    # stdin_open: true
    # tty: true
